### ISSUE TITLE
Issue trying to load tilt plugin

### ISSUE THREAD

**Issue by mthielman** [IndyJoeA/cbpi_Tilt#4]
I am getting the following error message when the system is running:

Failed to load plugin TiltHydrometerPlugin
__init__() got an unexpected keyword argument 'description'

**Comment by IndyJoeA** [comment]
That is due to the branch of CBPi you are running.  You are probably running on the base 3.0 version of CBPi which does not play well with plugins, so you will want to switch to the master branch which is more up to date.  There is an option to change to the master branch from the system screen in CBPi.  Try that and reboot, and that error should go away.

**Comment by mthielman** [comment]
Thanks, changing to master did enable the plugin. I have a couple other questions.

I will close this since original issue has been resolved. Thanks.
